# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 17:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30)),
                ('total_points', models.IntegerField()),
                ('gameweek_points', models.IntegerField()),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_defender', to='players.Player')),
                ('midfielder1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_midfielder1', to='players.Player')),
                ('midfielder2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_midfielder2', to='players.Player')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_owned', to=settings.AUTH_USER_MODEL)),
                ('striker1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_striker1', to='players.Player')),
                ('striker2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_striker2', to='players.Player')),
            ],
        ),
    ]
