# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20161117_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='gameweek_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
