# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20161117_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='defender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_defender', to='defenders.Defender'),
        ),
        migrations.AlterField(
            model_name='team',
            name='midfielder1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_midfielder1', to='midfielders.Midfielder'),
        ),
        migrations.AlterField(
            model_name='team',
            name='midfielder2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_midfielder2', to='midfielders.Midfielder'),
        ),
        migrations.AlterField(
            model_name='team',
            name='striker1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_striker1', to='strikers.Striker'),
        ),
        migrations.AlterField(
            model_name='team',
            name='striker2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_striker2', to='strikers.Striker'),
        ),
    ]
