# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strikers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='striker',
            name='position',
        ),
    ]
