# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defender',
            name='defender',
        ),
        migrations.RemoveField(
            model_name='midfielder',
            name='midfielder',
        ),
        migrations.RemoveField(
            model_name='striker',
            name='striker',
        ),
    ]
